### ISSUE TITLE
client.apps.create() outdated

### ISSUE THREAD

**Issue by arnldmthd** [SmartThingsCommunity/smartthings-core-sdk#87] opened 2021-01-06 20:45 UTC
app name seems to be optional in create app function
![image](https://user-images.githubusercontent.com/29730952/103818150-9ddd0900-5070-11eb-9ab0-a5568d9e3ca6.png)
![image](https://user-images.githubusercontent.com/29730952/103818175-a9c8cb00-5070-11eb-89cd-18879cb35b2d.png)
but still crashes
![image](https://user-images.githubusercontent.com/29730952/103818226-be0cc800-5070-11eb-9e7f-3f15ea3e363e.png)

**Comment by arnldmthd** [comment] 2021-01-06 21:22
Required parameters are these
![image](https://user-images.githubusercontent.com/29730952/103820987-fe227980-5075-11eb-8ef7-6cd5983a56af.png)

**Comment by rossiam** [comment] 2021-06-08 18:21
Closing as duplicate of #89.

**Closed by rossiam** 2021-06-08 18:21 UTC
